### PR TITLE
Add option to pass random and make name generation deterministic

### PR DESCRIPTION
**Pull request by entrusc**
Firstly: I really like your library, it is simple, has no dependencies on any third-party libraries and gets the job done nicely. Also it has a nice API interface. Only thing that I was missing was an option to create deterministic names based on some seed (e.g. create a name for a URL, so if I put in a URL like "google.com" I always want to get the same name).

I took the liberty of changing your library slightly to support deterministic name generation by optionally passing a `Random` instance to the `get()` method. With that the user can pass a `Random` with a specific seed if they wish to have deterministic results (also check the test case I added). If nothing is passed the library behaves exactly as before.

I hope this finds your approval. If not, let me know :)

### CODE REVIEW

**Comment by igr** [comment]
Thank you!

Got it! Let me try to add random in a separate function and not pass it to every method so as to keep Suppliers.

**Comment by entrusc** [comment]
Sure, if you find a more elegant way to implement it, be my guest :)

**Comment by igr** [comment]
Done @entrusc , just use `withRandom` method (as `withFoo` methods are for configuration) and thats it :)

I have just publish 2.2.0; I hope it will appear on the maven soon.

**Comment by entrusc** [comment]
Thanks @igr. Only thing that I noticed is that `rnd` is static which might cause problems when using multiple instances of `Nomen`. I'd suggest to make `rnd` an instance variable. Otherwise I'm happy with the implementation - thanks for adding the functionality. I really appreciate it! :)

**Comment by igr** [comment]
Dang! Fixing it!

**Comment by igr** [comment]
Right on time @entrusc ! Releasing 2.2.1 atm :) Thank you!

**Pull request closed without merging**
